services:
  backend:
    image: chitangchin/finbackend:dev
    ports:
      - "8080:8080"
    container_name: fastapi-backend
    environment:
      DATABASE_URL: "mssql+pyodbc://sa:${SA_PASSWORD}@database/FinancialBudgetApp?driver=ODBC+Driver+17+for+SQL+Server"
      SECRET_KEY: "${SECRET_KEY}"
      ALGORITHM: "#{ALGORITHM}"
      ACCESS_TOKEN_EXPIRE_MINUTES: 30
    depends_on:
      - database

  database:
    container_name: sqldb
    image: mcr.microsoft.com/mssql/server:2022-latest
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=${SA_PASSWORD}azureaihack2025!
      - MSSQL_PID=Developer

volumes:
  mssql_data: