services:
  backend:
    image: chitangchin/finbackend:latest
    ports:
      - "8080:8080"
    container_name: fastapi-backend

  database:
    container_name: sqldb
    image: chitangchin/finbackend_sql:latest
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=azureaihack2025!
      - MSSQL_PID=Developer

volumes:
  mssql_data: