name: Python Build and Test Validation

on:
  push:
    branches: [ '**' ]  # Run on all branches
  pull_request:
    branches: [ '**' ]  # Run on all PRs

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python '3.12'
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Test with pytest and generate coverage report
        run: |
          pytest --cov-report term --cov=app --cov-report=xml:__tests__/coverage.xml __tests__/

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: ./__tests__/coverage.xml
          fail_ci_if_error: false
