name: Python Build and Test Validation

on:
  push:
    branches: [ '**' ]  # Run on all branches
  pull_request:
    branches: [ '**' ]  # Run on all PRs

jobs:
  test:
    name: Build and Test
    runs-on: ubuntu-latest
    services:
      docker:
        image: docker:19.03.12
        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Cache pip packages
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose

      - name: Build Docker images
        run: |
          docker-compose build

      - name: Run Docker containers
        run: |
          docker-compose up -d
        env:
          SA_PASSWORD: ${{ secrets.SA_PASSWORD }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          ALGORITHM: ${{ secrets.ALGORITHM }}

      - name: Test with pytest and generate coverage report
        run: |
          pytest --cov-report term --cov=app --cov-report=xml:__tests__/coverage.xml __tests__/

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          file: ./__tests__/coverage.xml
          fail_ci_if_error: false
